
project_id = "ohnqfcbplmsypwnpxiga"
base_path = "/"

[functions.scrape-tenders]
verify_jwt = false

[functions.send-social-media]
verify_jwt = false

[functions.check-scraper-status]
verify_jwt = false

[functions.setup-db]
verify_jwt = false

[functions.sync-google-sheets-to-supabase]
verify_jwt = false

