// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohnqfcbplmsypwnpxiga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9obnFmY2JwbG1zeXB3bnB4aWdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzgwNDMxOTksImV4cCI6MjA1MzYxOTE5OX0.XdGT0rLGPTMEm_u89mDpU1MJjCMFQqA_aPGkWndEBv0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);